// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ihP3ttCUCRUY1hCYXC7seKbCTOrvBlY',
    appId: '1:501465790492:web:4033ce5a036fa944f107d9',
    messagingSenderId: '501465790492',
    projectId: 'flutter-assess',
    authDomain: 'flutter-assess.firebaseapp.com',
    storageBucket: 'flutter-assess.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6UdB-41qvY99F64pAEJO0rd4fwUVaC-E',
    appId: '1:501465790492:android:58755286cc52e1adf107d9',
    messagingSenderId: '501465790492',
    projectId: 'flutter-assess',
    storageBucket: 'flutter-assess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCULDaAiUgoRj8jt07i-qIsXHiJS5ySyeI',
    appId: '1:501465790492:ios:8624566fe719331ef107d9',
    messagingSenderId: '501465790492',
    projectId: 'flutter-assess',
    storageBucket: 'flutter-assess.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssessment',
  );
}
